# Generated by Django 2.1.5 on 2019-01-20 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_auto_20190111_0042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=128)),
                ('person_phone', models.CharField(max_length=30)),
                ('person_address', models.TextField(blank=True)),
                ('person_deceased_relationship', models.CharField(max_length=30)),
                ('contact_name', models.CharField(max_length=128)),
                ('contact_phone', models.CharField(max_length=30)),
                ('deceased_name', models.CharField(max_length=128)),
                ('deceased_date_birth', models.DateField(default=django.utils.timezone.localdate)),
                ('deceased_date_death', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_notes', models.TextField(blank=True)),
                ('pickup_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_notes', models.TextField(blank=True)),
                ('deleted', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(blank=True, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('file', models.FileField(blank=True, default='', upload_to='documents')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('terms', models.CharField(default='', max_length=30)),
                ('deleted', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(blank=True, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Quote')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Quote'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
